export const FETCH_RESTAURANT_SUCCESS = 'FETCH_RESTAURANT_SUCCESS'
export const ADD_OWN_RESTAURANT = 'ADD_OWN_RESTAURANT'
export const EDIT_OWN_RESTAURANT = 'EDIT_OWN_RESTAURANT'
export const DELETE_OWN_RESTAURANT = 'DELETE_OWN_RESTAURANT'